# Site settings
title: 9yu's pages
description: Resume Website
baseurl: "/" # the subpath of your site, e.g. /blog
url: http://Ohgyuchan.github.io # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: OH GYU CHAN
user_description: Software Engineer at Lorem Ipsum Dolor
user_title: 9yu's IT
email: gyu3637@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
